name: actions

on: [push]
permissions:
  contents: write


jobs:
  make-artifacts:
    name: Test make on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-12, macos-14]
        python-version: [3.9, 3.10, 3.11, 3.12]
    steps:
      - name: Install pybinding and test using normal installation
        continue-on-error: true
        run:
          pip list
          pip install pybinding-dev
          pip list
          python -c "import pybinding as pb; exit(pb.tests())"
      - name: Install matplotlib 3.9.1 and test
        continue-on-error: true
        run: |
          pip uninstall matplotlib -y
          pip install matplotlib==3.9.1
          pip list
          python -c "import pybinding as pb; exit(pb.tests())"
      - name: Download and unzip matplotlib 3.9.1
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            curl https://github.com/matplotlib/matplotlib/archive/refs/tags/v3.9.1.zip
            tar -xf v3.9.1.zip -C mpl
          elif [[ "${{ matrix.os }}" == "macos-12" ]] || [[ "${{ matrix.os }}" == "macos-14" ]]; then
            curl https://github.com/matplotlib/matplotlib/archive/refs/tags/v3.9.1.zip
            unzip v3.9.1.zip -d mpl
          else
            wget https://github.com/matplotlib/matplotlib/archive/refs/tags/v3.9.1.zip
            unzip v3.9.1.zip -d mpl
          fi
      - name: install matplotlib 3.9.1 and test
        run: |
          pip uninstall matplotlib -y
          pip install build
          pip list
          cd mpl/matplotlib-3.9.1
          python -m build --wheel
          pip install dist/*.whl
          pip list
          python -c "import pybinding as pb; exit(pb.tests())"
      - name: repair wheaal and test
        run: |
          pip uninstall matplotlib -y
          pip install delvewheel
          pip list
          cd mpl/matplotlib-3.9.1
          mkdir out
          delvewheel repait -w out dist/*.whl
          pip install out/*.whl
          pip list
          python -c "import pybinding as pb; exit(pb.tests())"