name: actions

on: [push]
permissions:
  contents: write


jobs:
  make-artifacts:
    name: Test make on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.10"
          - os: ubuntu-latest
            python-version: "3.11"
          - os: ubuntu-latest
            python-version: "3.12"
          - os: macos-12
            python-version: "3.11"
          - os: macos-14
            python-version: "3.11"
          - os: windows-latest
            python-version: "3.11"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: copy the testfile
        run: |
          mkdir ${{ matrix.os }}-${{ matrix.python-version }}-testfolder
          cp testfile ${{ matrix.os }}-${{ matrix.python-version }}-testfolder/${{ matrix.os }}-${{ matrix.python-version }}-testfile-1.txt
          cp testfile ${{ matrix.os }}-${{ matrix.python-version }}-testfolder/${{ matrix.os }}-${{ matrix.python-version }}-testfile-2.txt
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.python-version }}-artifact
          path: ${{ matrix.os }}-${{ matrix.python-version }}-testfolder/*.txt

  merge-artifacts:
    name: Merge all the artifacts
    runs-on: ubuntu-latest
    needs: [ make-artifacts ]
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: allfiles
      - name: merge the files
        run: |
          mkdir sources
          for dir in allfiles/*; do
            if [ -d "$dir" ]; then
                cp -r "$dir"/* sources/
            fi
          done
      - uses: actions/upload-artifact@v4
        with:
          name: sources
          path: sources

  test-artifacts:
    name: Test Open All
    runs-on: ubuntu-latest
    needs: [ merge-artifacts ]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: sources
          path: allarts
      - name: see artifacts
        run: ls allarts